// Generated by CoffeeScript 1.6.3
(function() {
  window.log = function(ob) {
    return console.log(ob);
  };

  window.getAsset = function(type, name) {
    return $.getJSON("assets/" + type + "/" + name + ".json").then(function(data) {
      return data.items;
    });
  };

}).call(this);
